name: Daily README Update

# Schedule the job to run once per day at midnight UTC
# (adjust the cron expression if you want a different time)
on:
  workflow_dispatch:    # ← allows you to click “Run workflow” in the Actions UI
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write   # grant write access to push back to the repo

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run daily update script
        env:
          GITHUB_TOKEN: ${{ secrets.MY_WRITE_TOKEN }}
        run: |
          python3 auto.py
